"""
Hardware Preprocessing — Filter Design and Signal Conditioning
===============================================================

This script provides the SOFTWARE-SIDE prototype of the hardware preprocessing
stage.

It:
1. Loads a generated two-channel signal.
2. Designs an adjustable Butterworth band-pass filter.
3. Applies the filter to both channels.
4. Compares raw and conditioned signals in the time/frequency domains.
5. Saves the conditioned signals for the TDOA module.

Important:
The initial cutoff frequencies are placeholders for system development.
They should be refined after examining real/generated signal spectra.
"""

from pathlib import Path
import argparse

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import butter, sosfiltfilt, welch


def design_bandpass(fs, lowcut, highcut, order=4):
    """Return a numerically stable Butterworth band-pass filter."""
    nyquist = fs / 2

    if not (0 < lowcut < highcut < nyquist):
        raise ValueError(
            f"Cutoffs must satisfy 0 < lowcut < highcut < {nyquist:.1f} Hz."
        )

    return butter(
        order,
        [lowcut / nyquist, highcut / nyquist],
        btype="bandpass",
        output="sos",
    )


def apply_filter(signal, sos):
    """Apply zero-phase filtering to avoid introducing phase distortion."""
    return sosfiltfilt(sos, signal)


def rms(signal):
    """Calculate RMS amplitude."""
    return float(np.sqrt(np.mean(signal ** 2)))


def plot_spectrum(signal, fs, label, ax):
    """Plot a one-sided power spectrum."""
    frequencies, power = welch(signal, fs=fs, nperseg=min(2048, len(signal)))
    ax.semilogy(frequencies, power + 1e-15, label=label)
    ax.set_xlabel("Frequency (Hz)")
    ax.set_ylabel("Power")
    ax.grid(True, alpha=0.25)


def process_file(input_file, output_file, fs, lowcut, highcut, order):
    data = pd.read_csv(input_file)

    required = {"time_s", "sensor_1", "sensor_2"}
    missing = required.difference(data.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    sensor_1 = data["sensor_1"].to_numpy(dtype=float)
    sensor_2 = data["sensor_2"].to_numpy(dtype=float)

    sos = design_bandpass(fs, lowcut, highcut, order)

    filtered_1 = apply_filter(sensor_1, sos)
    filtered_2 = apply_filter(sensor_2, sos)

    result = pd.DataFrame({
        "time_s": data["time_s"],
        "sensor_1_filtered": filtered_1,
        "sensor_2_filtered": filtered_2,
    })

    output_file = Path(output_file)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(output_file, index=False)

    # Time-domain comparison
    fig, axes = plt.subplots(2, 1, figsize=(11, 7), sharex=True)

    axes[0].plot(data["time_s"], sensor_1, linewidth=0.8)
    axes[0].plot(data["time_s"], sensor_2, linewidth=0.8, alpha=0.8)
    axes[0].set_title("Raw Two-Channel Signal")
    axes[0].set_ylabel("Amplitude")
    axes[0].legend(["Sensor 1", "Sensor 2"])
    axes[0].grid(True, alpha=0.25)

    axes[1].plot(data["time_s"], filtered_1, linewidth=0.8)
    axes[1].plot(data["time_s"], filtered_2, linewidth=0.8, alpha=0.8)
    axes[1].set_title(
        f"Conditioned Signal — {lowcut:g}–{highcut:g} Hz Band-Pass"
    )
    axes[1].set_xlabel("Time (s)")
    axes[1].set_ylabel("Amplitude")
    axes[1].legend(["Sensor 1", "Sensor 2"])
    axes[1].grid(True, alpha=0.25)

    fig.tight_layout()
    plot_path = output_file.with_name(output_file.stem + "_time_domain.png")
    fig.savefig(plot_path, dpi=180)
    plt.close(fig)

    # Frequency-domain comparison
    fig, ax = plt.subplots(figsize=(11, 5))
    plot_spectrum(sensor_1, fs, "Sensor 1 — Raw", ax)
    plot_spectrum(filtered_1, fs, "Sensor 1 — Filtered", ax)
    ax.set_title("Frequency-Domain Effect of Hardware Preprocessing")
    ax.legend()
    fig.tight_layout()

    spectrum_path = output_file.with_name(output_file.stem + "_spectrum.png")
    fig.savefig(spectrum_path, dpi=180)
    plt.close(fig)

    print(f"Input:  {input_file}")
    print(f"Output: {output_file}")
    print(f"Filter: {lowcut:g}–{highcut:g} Hz, order {order}")
    print(f"Sensor 1 RMS: {rms(sensor_1):.5f} → {rms(filtered_1):.5f}")
    print(f"Sensor 2 RMS: {rms(sensor_2):.5f} → {rms(filtered_2):.5f}")
    print(f"Saved plots beside output file.")


def main():
    parser = argparse.ArgumentParser(
        description="Prototype the hardware preprocessing stage."
    )
    parser.add_argument(
        "--input",
        default="../signal_generation/data/raw/case_0001_normal_none_snr5db_tdoa0.75ms.csv",
        help="Input CSV generated by signal_generator.py",
    )
    parser.add_argument(
        "--output",
        default="results/conditioned_signal.csv",
        help="Output CSV for TDOA processing",
    )
    parser.add_argument("--fs", type=int, default=8000)
    parser.add_argument("--lowcut", type=float, default=500)
    parser.add_argument("--highcut", type=float, default=3000)
    parser.add_argument("--order", type=int, default=4)

    args = parser.parse_args()

    process_file(
        input_file=args.input,
        output_file=args.output,
        fs=args.fs,
        lowcut=args.lowcut,
        highcut=args.highcut,
        order=args.order,
    )


if __name__ == "__main__":
    main()
